### ISSUE TITLE
Change version process to be more in time with DCM releases.

### ISSUE THREAD

**Issue by zomGreg** [enStratus/mixcoatl#129]
We discussed keeping the major version at 0, but implement something like: MAJOR.MINOR.PATCH. where MINOR = DCM release number, in this case 10. and PATCH be the DCM minor release number, which right now I think is 27. So we should be on version 0.10.27 of mixcoatl.

**Comment by bdwilliams** [comment]
New release 0.10.31 pushed to pypi (https://pypi.python.org/pypi/mixcoatl).
