### ISSUE TITLE
migrate dcm-* docs  to inline

### ISSUE THREAD

**Issue by zomGreg** [enStratus/mixcoatl#174]
migrate docs to pydoc for each dcm utility

**Comment by igable** [comment]
So this Issue means that we want to migrate `dcm-*` cli tools documentation from seperate restructured text files into inline sphinx readable doc strings. This will avoid having to make updates in two places.

**Comment by igable** [comment]
After some research there isn't a way to move the docs for the individual dcm-* tools inline. One has to be able to load them like a module and at the moment this can't be done. This should be left until there is a larger change to the DCM CLI.
