### ISSUE TITLE
dcm-list-users fails using Account Level Key (K.31)

### ISSUE THREAD

**Issue by gforghetti** [enStratus/mixcoatl#195]
Upgraded mixcoatl this morning and issued a dcm-list-users using an Account level API key.
Fails with: "mixcoatl.admin.user.UserException: A server error occurred processing your request: Fault occurred while processing."

Traceback (most recent call last):
  File "/usr/local/bin/dcm-list-users", line 28, in <module>
    results = User.all()
  File "/Library/Python/2.7/site-packages/mixcoatl/admin/user.py", line 274, in all
    raise UserException(r.last_error)
mixcoatl.admin.user.UserException: A server error occurred processing your request: Fault occurred while processing.

DCM_SSL_VERIFY=0
ES_API_VERSION=2015-01-28
ES_ENDPOINT=http://vagrant.vm:15000/api/enstratus/2015-01-28

dcm-list-users works fine with User level key.

**Comment by bdwilliams** [comment]
This is now fixed in k.32+
