### ISSUE TITLE
mixcoatl needs a dcm-describe-group

### ISSUE THREAD

**Issue by ewanlyall** [enStratus/mixcoatl#200]
There are commands to create roles/groups and we can assign roles to groups but we can't list existing assignments.

**Comment by bdwilliams** [comment]
I decided to make this `dcm-list-role-assignments`:

<pre>
(venv)➜  mixcoatl git:(develop) ✗ dcm-list-role-assignments
+----------+-----------------------------+-----------------------------------------------+----------------------------+--------+
| Group ID | Group Name                  | Description                                   | Roles Assigned             | Status |
+----------+-----------------------------+-----------------------------------------------+----------------------------+--------+
| 205      | Account Managers            | Marketing and product management              | 203 - Basic User           | ACTIVE |
| 206      | Trainee Developers          | New hire developers                           |                            | ACTIVE |
| 1430     | Cloud Subscription Admin    | Cloud Marketplace subscription administrators | 1 - Cloud Resource Manager | ACTIVE |
|          |                             |                                               | 1966 - Mine Only           |        |
| 201      | Administrators              | IT administrators with full access            | 202 - Admin                | ACTIVE |
| 200      | Cloud Operations            | Cloud operations team                         |                            | ACTIVE |
| 6600     | Read-only                   | RO                                            | 5900 - Read-only users     | ACTIVE |
| 203      | QA                          | Quality Assurance                             |                            | ACTIVE |
| 202      | Testers                     | Testing                                       | 2195 - Test                | ACTIVE |
| 9022     | Documentation army          | for testing purposes                          |                            | ACTIVE |
| 8105     | ms - API key                | aaaaaaaaaaaaaaaaaaaaaaaaa                     | 7402 - MS -  API key only  | ACTIVE |
| 1530     | Developer                   | Developer                                     | 202 - Admin                | ACTIVE |
| 9360     | test group                  | testing group                                 |                            | ACTIVE |
| 9429     | demo                        | test                                          | 1 - Cloud Resource Manager | ACTIVE |
| 600      | test access group           | testing modifications to user permissions     | 202 - Admin                | ACTIVE |
| 960      | JonGroup                    | Jon West's Group                              | 203 - Basic User           | ACTIVE |
|          |                             |                                               | 202 - Admin                |        |
| 1960     | Acme Academy - Basic Server | For a view only user for Acme Academy - Basic | 1950 - Server View Only    | ACTIVE |
+----------+-----------------------------+-----------------------------------------------+----------------------------+--------+
</pre>
