### ISSUE TITLE
cpu_count accessor missing from Server

### ISSUE THREAD

**Issue by zomGreg** [enStratus/mixcoatl#209]
======================================= FAILURES ========================================
_______________ TestBuildingBackendDCM.test_private_action_power_on_slow ________________

self = <nodes.building_backends.tests.test_dcm.TestBuildingBackendDCM object at 0x7528050>
private_cloud = <MagicMock name='DCM private cloud' id='122849232'>

    def test_private_action_power_on_slow(self, private_cloud):
        """
            Test power_on
            """
        node = MagicMock(id=57,
                         hostname="dcm-test-tc",
                         specs="",
                         status=NodeState.STOPPED)
        bb = BuildingBackendDCM(node, private_cloud)
>       bb.backend_action_power_on()

nodes/building_backends/tests/test_dcm.py:302:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
nodes/building_backends/dcm.py:289: in backend_action_power_on
    s_desc = s.description
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
```
self = <mixcoatl.decorators.lazy.lazy_property object at 0x4d09090>
instance = {'status': None, 'owning_groups': [{'group_id': 201}], 'last_error': None, 'pr..., 'keypair': None, 'cmAccount': None, 'firewalls': None, 'agent_version': None}
owner = <class 'mixcoatl.infrastructure.server.Server'>

    def __get__(self, instance, owner=None):
        myname = self.__name__

        if instance is None: return self

        if self._func is None:
            raise AttributeError, "unknown attribute %s" % myname
        # Check if we've already loaded from API
        if 'loaded' in instance.__dict__:
            if myname in dir(instance):
                return self._func(instance)
            else:
                raise AttributeError, "unknown attribute %s" % myname
        elif myname in instance.__dict__:
            return self._func(instance)
        else:
            if getattr(instance, instance.PRIMARY_KEY) is not None:
                try:
                    instance.load()
                except AttributeError as detail:
                    if instance.last_error is not None:
                        return instance.last_error
                    else:
>                       raise LazyPropertyException(detail)
E                       LazyPropertyException: Key found without accessor: cpu_count
```

/home/vagrant/env/lib/python2.6/site-packages/mixcoatl/decorators/lazy.py:51: LazyPropertyException

**Comment by igable** [comment]
Fixed by ad5b29ccc525093 after release 0.10.50.
