### ISSUE TITLE
dcm-create-server - network_id

### ISSUE THREAD

**Issue by sonicepk** [enStratus/mixcoatl#216]
I am trying to create a server using dcm-server-create and the dcm portal returns an error message of "[400] Multiple possible networks found, use a network id to specify the network". The only "networking" argument for dcm-create-server is --vlan. Interesting if I set the --vlan = a valid network id, the mixcoatl script does not complain but the DCM portal still has the network_id error message. 
Happy to provide any debugging......

Regards
Eoin

```
dcm-list-networks --region 17
-----------+-----------+-----------------------------+--------------------------------------+----------+-----------------+
| Network ID | Region ID | Name                        | Provider ID                          | Type     | Network Address |
+------------+-----------+-----------------------------+--------------------------------------+----------+-----------------+
|| 115        | 17        | default                     | b595e45a-e509-4db2-85f0-e846b5f95742 | STANDARD | 0.0.0.0/0       |

dcm-create-server --machineimage 21 --datacenter 29 --name 'ek_api' --description 'ek API testing' --productid 'm1.large' --budgetid 600 --vlan 115
method: POST
data = {"launch": [{"dataCenter": {"dataCenterId": "29"}, "product": {"productId": "m1.large"}, "name": "ek_api", "vlan": {"vlanId": "115"}, "budget": "600", "machineImage": {"machineImageId": "21"}, "description": "ek API testing"}]}
headers: content-length = 44
headers: x-es-request = msp0x21b54ea0-edaa-4eda-b68f-b1cca6e7a27d
headers: date = Mon, 27 Apr 2015 17:03:46 GMT
headers: content-type = application/json;charset=UTF-8
headers: connection = keep-alive
headers: server = Dell Cloud Manager
977
```

**Comment by zomGreg** [comment]
Hello sonicepk,

We're a bit backlogged on a couple of production related items now and we're working to bring a full-time mixcoatl maintainer onboard in the very near future to help expedite requests like this.

Thank you so much for using mixcoatl, DCM, and the cloud. We'll get back to you as soon as we can.

Greg

**Comment by ewanlyall** [comment]
I actually think this is an issue with the API, rather than mixcoatl. https://enstratus.fogbugz.com/default.asp?6774

That being said, dcm-create-server should have the option to specify both a network ID and subnet ID

**Comment by sonicepk** [comment]
A work around is to use dcm-post, which allows you to specify networkid and subnetid. 

dcm-post --json create-ubuntu-small-good.json infrastructure/Server

cat create-ubuntu-small-good.json
{
   "launch": [
     {
       "dataCenter": { "dataCenterId": 29 },
        "product": {"productId": 20033},
       "network": { "networkId": 115},
       "subnet": { "subnetId": 115},
         "firewalls": [{"firewallId": 24 }],
         "name": "ek-1",
        "userData": "",
       "budget": 600,
       "machineImage": { "machineImageId": 20 },
       "description": "ek api"
     }
   ]
}

**Comment by igable** [comment]
@sonicepk Thanks for you patience on this, and thanks for pinging the issue again today. There is a new release (0.10.50.1) pushed to PyPI that fixes this. You can now do:

```
dcm-create-server --network 115 --subnet 115
```

Note that there is auto correct error on your name in the [ChangeLog](https://github.com/enStratus/mixcoatl/blob/0aef8d164329e1db4189611b7d05df285f5ce84b/CHANGELOG.md#33) that will be corrected in the next release (next week). Apologies for that.

**Comment by sonicepk** [comment]
Thanks Ian, Works great. 
dcm-create-server -p 20033 -d 29 -e 115 -s 115 -n ek-machine-api -b 600 -m 20 -D "test"
