### ISSUE TITLE
Drop termcolor as dependency?

### ISSUE THREAD

**Issue by igable** [enStratus/mixcoatl#252]
@zomGreg and @bdwilliams,  termcolor was introduced as a dependency for handsfree installer so that things like this could be done:

```python
print "{:}".format('[ ' + colored('OK', 'green') + ' ]')
```

termcolor doesn't have native OS packaging on Ubuntu and likely other distros. For the sake of simplification, I propose going black and white and dropping this dependency? Can you gentlemen give me your thoughts on this?

**Comment by bdwilliams** [comment]
imo just get rid of all the dependencies related to anything in the utils/ directory

**Comment by igable** [comment]
Thanks Brian. termcolor is the only dep that is put on the whole package from things `utils/` . I'm going to go ahead and remove it. If @zomGreg feel differently we can backtrack later.

**Comment by igable** [comment]
The way I'm going to deal with this is by removing `termcolor==1.1.0` from setup.py and leaving `termcolor >= 1.1.0` in requirements.txt . This is similar to how we deal with requirements for things like nose.
