### ISSUE TITLE
dump iara-stable branch?

### ISSUE THREAD

**Issue by igable** [enStratus/mixcoatl#258]
I would like to dump the stable branch? Is there any reason to keep it @zomGreg and @bdwilliams ? My goal is to keep a few recent release branches around, for convenience but as they get older to remove them. They can always be patched by starting form the tags.

**Comment by igable** [comment]
@bdwilliams thoughts on this?

**Comment by jimsander** [comment]
The only reason I can think of would be to facilitate any migration effort
with our last Iara client.  We have it installed on the one jump box for
now, and that SHOULD be enough but I'd like to hedge in case they
accidentally blue or away.

**Comment by igable** [comment]
This is good enough reason to keep it around for a good long while. There is no real cost to it. Thanks for the info @jimsander . I'm closing the issue for now. It can be reopened when we are certain it's long dead.
