### ISSUE TITLE
Assign budget using friendly name?

### ISSUE THREAD

**Issue by zomGreg** [enStratus/mixcoatl#40]
I don't know if I like this as a feature. If I'm understanding it correctly, you can pass in the 'name' of the budget code like 'Default' and we'll look up the ID of that code and then assign that to the volume.

Seems confusing

https://github.com/enStratus/mixcoatl/blob/master/bin/dcm-create-volume#L14

**Comment by bdwilliams** [comment]
@zomGreg , can you tell me what the remaining required task is on this issue or close it?

**Comment by zomGreg** [comment]
not going to implement now. Too much hassle. Will revisit.
