### ISSUE TITLE
help syntax incorrect

### ISSUE THREAD

**Issue by jimsander** [enStratus/mixcoatl#77]
usage: dcm-create-volume [-h] (--budgetid BUDGETID | --budgetname BUDGETNAME)
                         [--datacenter DATACENTER] [--description DESCRIPTION]
                         [--name NAME] [--size SIZE]

[] brackets imply optional

datacenter, name and size are not optional 
getting usage message if 'description' flag is not used

**Comment by bdwilliams** [comment]
Changed to:

<pre>
(venv)[brian:...om/bdwilliams/venv/mixcoatl]$ dcm-create-volume -h  
usage: dcm-create-volume [-h] --budgetid BUDGETID --datacenter DATACENTER
                         --description DESCRIPTION --name NAME --size SIZE

optional arguments:
  -h, --help            show this help message and exit

required arguments:
  --budgetid BUDGETID, -b BUDGETID
                        Budget ID.
  --datacenter DATACENTER, -d DATACENTER
                        Data Center ID in which to create the volume.
  --description DESCRIPTION, -D DESCRIPTION
                        The description of the volume.
  --name NAME, -n NAME  The name of the volume.
  --size SIZE, -s SIZE  The size of the volume in GB.
</code>
